name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=quay.io/ansible/awx-ee:${{ github.event.release.tag_name }}

      - name: Apply all tags
        run: |
         docker tag quay.io/ansible/awx-ee:${{ github.event.release.tag_name }} quay.io/ansible/awx-ee:latest
         docker tag quay.io/ansible/awx-ee:${{ github.event.release.tag_name }} quay.io/ansible/ansible-navigator-demo-ee:${{ github.event.release.tag_name }}
         docker tag awx-ee:${{ github.event.release.tag_name }} ansible-navigator-demo-ee:latest

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/ansible/awx-ee:${{ github.event.release.tag_name }}
         docker push quay.io/ansible/awx-ee:latest
         docker push quay.io/ansible/ansible-navigator-demo-ee:${{ github.event.release.tag_name }}
         docker push quay.io/ansible/ansible-navigator-demo-ee:latest
